/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("hahn.crypto.java-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("hahn.crypto.aes.encrypt.Main")
}
