/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hahn.crypto.keygenerator;

import hahn.crypto.utilities.AESCryptoUtil;

import javax.crypto.SecretKey;
import java.io.IOException;
import java.security.NoSuchAlgorithmException;

public class Main {

    public static void main(String[] args) {
        new Main().execute(args[0]);
    }

    private void execute(String keyPath) {

        try {
            SecretKey secretKey = AESCryptoUtil.generateRandomKey();
            AESCryptoUtil.storeKey(secretKey, keyPath);
        } catch (NoSuchAlgorithmException | IOException e) {
            throw new RuntimeException(e);
        }

    }

}
